### ISSUE TITLE
TypeError: Cannot call method 'setOptions' of undefined

### ISSUE THREAD

**Issue by andregeges** [jmdobry/angular-cache#158]
Hi it is running well with browser view, but after i run on mobile device i got this error 

TypeError: Cannot call method 'setOptions' of undefined

**Comment by jmdobry** [comment]
Make sure you check that the cache has been created before you do anything with it:

```js
if (!DSCacheFactory.get('myCache')) {
  DSCacheFactory('myCache', { storageMode: 'localStorage', maxAge: 10000, deleteOnExpire: 'aggressive' });
}
DSCacheFactory.get('myCache').put('item', 'value');
```

----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error/stack trace, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-cache).
