### ISSUE TITLE
Data loaded in the onExpire function is only available at the next request

### ISSUE THREAD

**Issue by ChristopherBrix** [jmdobry/angular-cache#167]
When the cache is set to the passive deletion mode, onExpire is only called if the cached item is requested.
But even if the onExpire code created a new entry for the current key, the get method always returns undefined. Only the next reload will work correctly (if the item didn't expire again).

Changing line 274 from *value = undefined* to *value = this.get(key);* did the trick for me, but it's not an optimal solution since it could create an infinite loop for very small maxAge values.

**Comment by jmdobry** [comment]
From the point of view of the user calling `get(key)` for an expired item in `passive` mode, the item _is not in the cache_, even if angular-cache is lazily removing the item from the cache at the time of the request. angular-cache cannot make any assumptions about what kind a code will be executed in `onExpire`. The user could very well be doing asynchronous things, such as retrieving fresh data from the server to put it back into the cache. `get` will return `undefined` if the item is expired. Changing this behavior would be a breaking change. Just before calling `get(key)`, you can call `touch(key)` even if it is expired (assuming you're in passive mode), and the `get` call will return the item. You could create yourself a helper function to do this for you.

```js
function touchGet(cacheOrCacheId, key) {
  if (typeof cacheOrCacheId === 'string') {
    CacheFactory.get(cacheOrCacheId).touch(key);
    return CacheFactory.get(cacheOrCacheId).get(key);
  } else {
    cacheOrCacheId.touch(key);
    return cacheOrCacheId.get(key);
  }
}
```

**Comment by jmdobry** [comment]
Maybe revisit this for 5.0

----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-cache).
