### ISSUE TITLE
Request for some examples for using angular cache in ngResource

### ISSUE THREAD

**Issue by dhiva** [jmdobry/angular-cache#171]
Hi,

I understand that the latest release has support to ngResource. Could you please add some examples to the document page on using angular cache in $resource. It would really be helpful.

Thank you.

**Comment by ahmed-abdulmoniem** [comment]
How can we use it in ngResource?

**Comment by jmdobry** [comment]
With the knowledge that angular-cache can be used anywhere that $cacheFactory can be used (it's a drop in replacement for $cacheFactory), then the [ngResource documentation](https://code.angularjs.org/1.3.12/docs/api/ngResource/service/$resource) for using $cacheFactory with ngResource and various blog posts and [stackoverflow answers](http://stackoverflow.com/a/17060344) about the topic should provide sufficient examples.

ngResource actions support the same options as `$http(config)`, so your knowledge of that and its documentation also tell you that there is a `cache` option that you can set to an instance of a cache (either one created by $cacheFactory or by angular-cache), and the cache will be used by the resource.

**Comment by jmdobry** [comment]
Here's an example I found on Stack Overflow: http://stackoverflow.com/questions/30466569/angular-cache-ng-resource-transformresponse-before-caching

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-cache).
