### ISSUE TITLE
How to extend cache instance's functionalities?

### ISSUE THREAD

**Issue by jenux** [jmdobry/angular-cache#176]
When create a cache I want add a customized method for it, like 
```
var profileCache = CacheFactory('profileCache')
profileCache.generateKey = function(profileName, profileAge) { return ...; }
```
Any way for me to add generateKey() to profileCache?
Thanks

**Comment by jmdobry** [comment]
I don't know of anything preventing you from doing exactly as you described in your example.

**Comment by jmdobry** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-cache).
