### ISSUE TITLE
angular cache can't be used with rc version of angular 1.4

### ISSUE THREAD

**Issue by myagoo** [jmdobry/angular-cache#177]
Would  it be possible to specify a peerDependency which include rc versions of angular 1.4 with something like ">=1.x ||  >1.4.0-rc" ?

Me and my team are unable to npm install our project due to this issue.

I made a pull request for this : #178

**Comment by jmdobry** [comment]
Are you going to be around to maintain angular-cache's `package.json` when there's a 1.4.1-beta.3, or a 1.4.2-rc.2, or a 1.5.0-rc, or a 1.6.0-rc? Because I really don't want to have to do that. Frankly, I think it's dumb to make allowances for a specific pre-release version of a dependency, when as a library author I do not recommend users install pre-release versions for my libraries' dependencies, as I have not tested them.

On the other hand, I totally understand that you want to be able to use 1.4 with angular-cache. It's unfortunate that npm doesn't have a flag that would allow 1.4.0-rc.1 to satisfy the >=1.x comparator (maybe it does, I haven't found it).

In the end, if you really want npm to install angular-cache, I recommend that you fork angular-cache until such time as Angular 1.4 has a version that satisfies the >=1.x comparator. Or, install angular-cache with Bower, as Bower will allow you to install 1.4.0-rc.1 all day.
