### ISSUE TITLE
Storage Medium

### ISSUE THREAD

**Issue by sriramjothimani** [jmdobry/angular-cache#196]
I see the below  behavior when I choose to have localStorage as the storage medium. I would like to double check, if that is what it is intended to be or am misinterpreting it.

So I create a cache as follows,

var cnCache = CacheFactory("CNCache",{
                         maxAge: 24 * 60 * 60 * 1000 
                        ,deleteOnExpire: 'aggressive' 
                        ,storageMode: 'localStorage'  
                    });

And set the following attribute in cache, cnCache.put("myAttr","myValue");

Once the attribute is set am able to find it from localStorage. All is well till now.

Now I refresh the page and try to get the CNCache from cache factory which does not exist. But the data (myAttr) is still in localStorage. So I have been pushed to recreate the cache with the same name and options, again once the page is refreshed. 

Now everything is back in shape, we were able to get hold of the attributes from the localStorage which was set before the page refresh. 

Am not clear where in, though we set storageMode as localstorage it will not retain the cache but just the localStorage. And to access it every time we need to recreate the cache with the same options.  

Please clarify.

**Comment by jmdobry** [comment]
> to access it every time we need to recreate the cache with the same options.

That right there is the truth of JavaScript in the browser. localStorage can only hold strings. The JavaScript objects and methods created when you run `var cnCache = CacheFactory("CNCache",{...});` cannot be serialized to localStorage (and they are wiped from memory when you refresh), so every time your apps boots up, it needs to execute `var cnCache = CacheFactory("CNCache",{...});`, which will then be able to access any data that was previously saved to localStorage.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-cache).
