### ISSUE TITLE
Example to replace Angular's built-in $templateCache?

### ISSUE THREAD

**Issue by stnever** [jmdobry/angular-cache#197]
As far as I can tell there's no way to get the keys in Angular's default $templateCache. [This stackoverflow question](http://stackoverflow.com/questions/18447713/is-there-a-way-to-get-all-of-the-keys-out-of-a-cache-in-angular-specifically-th) led me to believe that I could somehow replace that cache with AngularCache and gain access to the `keys()` method.

Are there any pointers on how to do that? The readme mentions how to fiddle with the cache in the `$http` service, but I don't know what service (if any) is responsible for using the templates.

(the problem I'm trying to solve is to override some cache keys in the presence of others. For example, if there are two keys `menu.html` and `custom/menu.html` I want to override the former with the contents of the latter. Unfortunately I don't know beforehand what pages, if any, are to be overridden.)

**Comment by jmdobry** [comment]
You might try something like this:

```javascript
myApp.config(['$provide', function ($provide) {
  var customTemplateCache;
  $provide.decorator('$templateCache', function ($delegate, CacheFactory) {
    customTemplateCache = customTemplateCache || CacheFactory('customTemplateCache', { /*config*/ });
    return customTemplateCache;
  });
}]);
```

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-cache).
