### ISSUE TITLE
Allow service injection in storageImpl

### ISSUE THREAD

**Issue by aaaaahaaaaa** [jmdobry/angular-cache#198]
Hi,

It would be nice to have a way to inject another service to be used as a polyfill in 'storageImpl', like 'angular-local-storage' for instance. I woudn't really know actually how to do that, but I was thinking of something like the 'resolve' option you find with some Angular providers.

    .config(function(CacheFactoryProvider) {
		angular.extend(CacheFactoryProvider.defaults, {
			maxAge: 60 * 60 * 1000,
			deleteOnExpire: 'aggressive',
			storageMode: 'localStorage',
			storageImpl: function(localStorageService) {
				return {
					getItem: localStorageService.get,
					setItem: localStorageService.set,
					removeItem:  localStorageService.remove
				};
			}
		});
	})

**Comment by aaaaahaaaaa** [comment]
Hum, my comparison with 'resolve' probably doesn't make any sense actually. I guess my question is a general Angular question of how to inject a service in 'config' block...

**Comment by jmdobry** [comment]
http://stackoverflow.com/a/21650337

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-cache).
