### ISSUE TITLE
Cachefactory doesnt works inside app.run

### ISSUE THREAD

**Issue by luispaulopinto** [jmdobry/angular-cache#202]
Hello, 

I`m trying to access some data from cache on app.run, but looks like Cachefactory doesnt works there.

**Comment by jmdobry** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-cache).
