### ISSUE TITLE
trouble: bundle with r.js not works

### ISSUE THREAD

**Issue by KhodeN** [jmdobry/angular-cache#203]
Your `build_example/r.js` example not works. 

In console there is error:
```
Uncaught Error: Mismatched anonymous define() module: function (__WEBPACK_EXTERNAL_MODULE_1__) {
```

Unfortunately in my project there is same error after create bundle((

I know, errors is in 
```javascript
if(typeof define === 'function' && define.amd)
		define(["angular"], factory);
```

For bundled file requirejs expected this syntax:
```javascript
define('/path/to/angular-cache/dist/angular-cache', ['angular'], factory)
```

**Comment by jmdobry** [comment]
I just did:

1. `clone git@github.com:jmdobry/angular-cache.git && cd angular-cache`
1. `npm install`
1. `grunt build`
1. `cd build_examples/r.js`
1. `r.js -o require.config.js`

and it worked, including opening `index.html` and running the code. So...closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-cache, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-cache).

**Comment by KhodeN** [comment]
Please open index.html and switch to use production version (bundled).

Just this way:

```html
<head>
  <title>My App</title>
  <!-- load scripts dynamically -->
  <!-- <script data-main="main" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.17/require.min.js"></script> -->

  <!-- load bundled scripts -->
<script data-main="bundle" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.17/require.min.js"></script>
</head>
````

**Comment by jmdobry** [comment]
I've run into this before, which is why I filed webpack/webpack#989, but I thought I fixed it...
